-- Active: 1697098245110@@127.0.0.1@3306@小学教务系统
-- 创建教师表

-- 创建教师用户表
CREATE TABLE
    teacher_users (
        t_username VARCHAR(255) DEFAULT NULL PRIMARY KEY,
        t_password VARCHAR(255) DEFAULT NULL,
        `LEVEL` INT(11) DEFAULT 1
    );

CREATE TRIGGER AFTER_TEACHERS_INFO_INSERT AFTER INSERT 
ON TEACHER FOR EACH ROW BEGIN INSERT 
	INSERT
	INSERT
	INSERT
	INSERT
	INSERT
	INSERT
	INSERT INTO
	    teacher_users (t_username, t_password, level)
	VALUES (NEW.t_id '123456', 1);
	END;


CREATE TRIGGER AFTER_TEACHERS_INFO_DELETE AFTER DELETE 
ON TEACHER FOR EACH ROW BEGIN DELETE 
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE
	DELETE FROM teacher_users
	WHERE t_id = OLD.t_id;
	END;


CREATE Table
    hobbies_class(
        hc_id INT(11) NOT NULL PRIMARY KEY,
        hc_name VARCHAR(255) NOT NULL
    );